# Generated by Django 6.0.5 on 2026-07-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointtransaction",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Human-readable context, kept because the ledger outlives what it refers to. A Spendium purchase is anonymised after thirty days, so without this the player's history reads as an unexplained row of numbers.",
                max_length=200,
            ),
        ),
    ]
