# Generated by Django 6.0.5 on 2026-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="sqid",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
