# Generated by Django 6.0.5 on 2026-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_player_auth_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="accounts_em_token_h_461c72_idx",
            old_name="accounts_em_token_h_idx",
        ),
        migrations.AddField(
            model_name="membership",
            name="tier",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("sustaining_member", "Sustaining Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
