# Generated by Django 6.0.5 on 2026-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_surveyconfig_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="submit_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
