# Generated by Django 6.0.5 on 2026-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_surveyresponse_submit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyconfig",
            name="min_survey_threshold",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Minimum survey responses a criterion must have to count toward declaration points.",
            ),
        ),
    ]
