# Generated by Django 6.0.5 on 2026-07-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0005_update_criterion_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="criteria_are_provisional",
            field=models.BooleanField(
                default=True,
                help_text="True while the criteria are founder-set rather than decided by the membership. Shown to players, because members determining the criteria is the point of HF and a temporary exception should look like one.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="criteria_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Bumped whenever the question set changes. Responses record the version they were given under, so answers to different questions are never averaged together as though they were the same.",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="criteria_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The Category.criteria_version in force when this was answered.",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The response was anchored to evidence the platform could check — in Spendium, a receipt showing the player actually bought the product. Recorded as a flag rather than a link so the anchor survives the purchase being anonymised.",
            ),
        ),
    ]
