# Generated by Django 6.0.5 on 2026-07-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_category_criteria_are_provisional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="What this criterion is worth, in points per dollar. Set by the membership, not by engineering. The ceiling of 999.99 is kept deliberately: it is not a limit on what members may decide, but a point at which a proposal has to be argued for rather than merely entered. Widen the column if that argument is ever won.",
                max_digits=5,
            ),
        ),
    ]
