# Generated by Django 6.0.5 on 2026-08-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("surveys", "0007_alter_criterion_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyresponse",
            name="criteria_version",
        ),
        migrations.AddField(
            model_name="category",
            name="subject_type",
            field=models.ForeignKey(
                blank=True,
                help_text="What these questions are about — Candidate, Product, Store. Null means every subject in the game, which is what Polium relied on when Candidate was its only rateable thing.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="survey_categories",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="criterionanswer",
            name="criteria_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The version of this criterion's category when it was answered. Per answer rather than per response, because a subject may be asked questions from several categories and each keeps its own version — one integer on the response cannot describe two of them.",
            ),
        ),
    ]
