# Generated by Django 6.0.5 on 2026-07-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("active_engagement", models.PositiveIntegerField(default=0)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("active_engagement", models.PositiveIntegerField(default=0)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Health, personal care and similar. Raises the k-anonymity bar before aggregates derived from this category may be published.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="spendium.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        help_text="[Brand] [Product Name] [Variant] — no size. Size variants collapse into a single product line.",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("retired", "Retired"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_source",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini interpretation"),
                            ("upc_lookup", "UPC / open database lookup"),
                            ("admin", "Admin"),
                            ("player", "Player supplied"),
                        ],
                        default="gemini",
                        max_length=20,
                    ),
                ),
                (
                    "reformulated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Reserved for the case where a product changes formulation under the same name. Not yet acted on.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="spendium.manufacturer",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this record is retired into another. Ratings and aliases resolve through this link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="spendium.product",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="spendium.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUpc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(db_index=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcs",
                        to="spendium.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product UPC",
                "verbose_name_plural": "product UPCs",
            },
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.CharField(help_text="Verbatim, as printed.", max_length=300),
                ),
                (
                    "raw_text_normalised",
                    models.CharField(db_index=True, max_length=300),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("player", "Player confirmation"),
                            ("adjudication", "Model adjudication"),
                            ("admin", "Admin"),
                        ],
                        default="player",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("authoritative", "Authoritative"),
                            ("demoted", "Demoted"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                ("confirmation_count", models.PositiveIntegerField(default=0)),
                ("contradiction_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="spendium.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="The retailer that printed this string. Null means a global alias, matched only when no retailer-scoped alias applies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_aliases",
                        to="spendium.store",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product aliases",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="spendium_pr_status_0cd905_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["canonical_name"], name="spendium_pr_canonic_f33146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(
                fields=["store", "raw_text_normalised"],
                name="spendium_pr_store_i_762f61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(fields=["status"], name="spendium_pr_status_a56f7d_idx"),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("store__isnull", False)),
                fields=("store", "raw_text_normalised"),
                name="unique_store_scoped_alias",
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("store__isnull", True)),
                fields=("raw_text_normalised",),
                name="unique_global_alias",
            ),
        ),
    ]
