# Generated by Django 6.0.5 on 2026-07-25 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0002_manufacturer_store_productcategory_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymisedPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("purchased_at", models.DateTimeField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("anonymised_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymised_purchases",
                        to="spendium.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnonymisedLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.CharField(help_text="Verbatim, as printed.", max_length=300),
                ),
                (
                    "raw_text_normalised",
                    models.CharField(db_index=True, max_length=300),
                ),
                (
                    "interpreted_name",
                    models.CharField(
                        blank=True,
                        help_text="The model's reading of the raw text.",
                        max_length=300,
                    ),
                ),
                (
                    "match_tier",
                    models.CharField(
                        choices=[
                            ("alias", "Tier 0 — exact alias"),
                            ("fuzzy", "Tier 1 — fuzzy match"),
                            ("adjudicated", "Tier 2 — model adjudication"),
                            ("player", "Tier 3 — player confirmed"),
                            ("unmatched", "Unmatched"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_items",
                        to="spendium.product",
                    ),
                ),
                (
                    "anonymised_purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="spendium.anonymisedpurchase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        help_text="Transaction time, from the receipt."
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image_phash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Perceptual hash for duplicate detection. Outlives the image itself, which is deleted within IMAGE_RETENTION_HOURS.",
                        max_length=64,
                    ),
                ),
                ("image_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anonymise_after",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record must be anonymised. A sweeper catches any purchase whose scheduled task was lost.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="spendium.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.CharField(help_text="Verbatim, as printed.", max_length=300),
                ),
                (
                    "raw_text_normalised",
                    models.CharField(db_index=True, max_length=300),
                ),
                (
                    "interpreted_name",
                    models.CharField(
                        blank=True,
                        help_text="The model's reading of the raw text.",
                        max_length=300,
                    ),
                ),
                (
                    "match_tier",
                    models.CharField(
                        choices=[
                            ("alias", "Tier 0 — exact alias"),
                            ("fuzzy", "Tier 1 — fuzzy match"),
                            ("adjudicated", "Tier 2 — model adjudication"),
                            ("player", "Tier 3 — player confirmed"),
                            ("unmatched", "Unmatched"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "disambiguation_state",
                    models.CharField(
                        choices=[
                            ("not_needed", "No disambiguation needed"),
                            ("pending", "Awaiting player confirmation"),
                            ("resolved", "Resolved by player"),
                        ],
                        default="not_needed",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_items",
                        to="spendium.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="spendium.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="anonymisedpurchase",
            index=models.Index(
                fields=["purchased_at"], name="spendium_an_purchas_8a470f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["player", "purchased_at"], name="spendium_pu_player__3d3a13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaselineitem",
            index=models.Index(
                fields=["disambiguation_state"], name="spendium_pu_disambi_40192a_idx"
            ),
        ),
    ]
