# Generated by Django 6.0.5 on 2026-07-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0003_anonymisedpurchase_anonymisedlineitem_purchase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strong_match_score",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="At or above this score (0-100) a match is accepted silently, with no prompt.",
                    ),
                ),
                (
                    "weak_match_score",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="At or above this, the best candidate is used but the player is offered a chance to correct it.",
                    ),
                ),
                (
                    "noise_floor_score",
                    models.PositiveIntegerField(
                        default=55,
                        help_text="Candidates below this are hidden entirely. Showing implausible options produces confusion, not signal.",
                    ),
                ),
                (
                    "candidate_limit",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="How many candidates FTS5 narrowing hands to scoring. Caps matching cost so it does not grow with the catalogue.",
                    ),
                ),
                (
                    "prompt_budget",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum disambiguation prompts shown per receipt. Players who see fifteen icons ignore all of them.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching configuration",
                "verbose_name_plural": "Matching configuration",
            },
        ),
    ]
