# Generated by Django 6.0.5 on 2026-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0005_product_fts"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="receipt_image",
            field=models.FileField(
                blank=True,
                help_text="Transient. Deleted within IMAGE_RETENTION_HOURS of processing, per the published privacy policy.",
                null=True,
                upload_to="receipts/%Y/%m/",
            ),
        ),
    ]
