# Generated by Django 6.0.5 on 2026-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0006_purchase_receipt_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="adjudication_candidates",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Candidates offered per item in the Tier 2 adjudication call. Set to 0 to disable adjudication entirely.",
            ),
        ),
    ]
