# Generated by Django 6.0.5 on 2026-07-26 00:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0007_matchconfig_adjudication_candidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="processing_problems",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Arithmetic and legibility problems found during extraction. Shown to the player rather than hidden — they are the only person who can tell whether a reading is actually wrong.",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting to be read"),
                    ("processed", "Read"),
                    ("failed", "Could not be read"),
                ],
                db_index=True,
                default="pending",
                help_text="Extraction runs in a task, so a purchase exists before it has been read.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchased_at",
            field=models.DateTimeField(
                help_text="Transaction time, from the receipt. Holds the upload time until the receipt has been read."
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
