# Generated by Django 6.0.5 on 2026-07-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0008_purchase_processing_problems_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="auto_merge_score",
            field=models.PositiveIntegerField(
                default=95,
                help_text="Two unverified records scoring at least this against each other are merged without asking. Deliberately higher than the strong match bar: a wrong merge is harder to notice than a missed one.",
            ),
        ),
        migrations.AddField(
            model_name="productalias",
            name="needs_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set when players keep contradicting this alias. A string several people disagree about needs a human, not another vote.",
            ),
        ),
        migrations.CreateModel(
            name="AliasConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="spendium.productalias",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alias", "player"), name="one_alias_vote_per_player"
                    )
                ],
            },
        ),
    ]
