# Generated by Django 6.0.5 on 2026-07-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0009_matchconfig_auto_merge_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="retro_batch_size",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Line items re-examined per retro-matching run, per layer. Retro-matching is never urgent, so a modest batch that always finishes beats a large one that times out halfway.",
            ),
        ),
    ]
