# Generated by Django 6.0.5 on 2026-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0010_matchconfig_retro_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymisedlineitem",
            name="retro_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When retro-matching last examined this line. Ordering by it is what makes successive runs work through the backlog instead of re-examining the same head of the queue forever.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaselineitem",
            name="retro_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When retro-matching last examined this line. Ordering by it is what makes successive runs work through the backlog instead of re-examining the same head of the queue forever.",
                null=True,
            ),
        ),
    ]
