# Generated by Django 6.0.5 on 2026-07-26 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0011_anonymisedlineitem_retro_checked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRatingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_on", models.DateField(db_index=True)),
                ("score", models.DecimalField(decimal_places=3, max_digits=4)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("verified_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_snapshots",
                        to="spendium.product",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_on"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "taken_on"),
                        name="one_snapshot_per_product_per_day",
                    )
                ],
            },
        ),
    ]
