# Generated by Django 6.0.5 on 2026-07-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0012_productratingsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="points_awarded",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Set once, when the receipt is first read. Its presence is what stops a reprocessed or re-matched purchase paying out twice.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt photo"),
                    ("qr", "QR code at the till"),
                    ("self_report", "Self-reported"),
                    ("online", "Online order"),
                ],
                default="receipt",
                help_text="How the purchase was evidenced. Only the receipt path exists so far; the others earn at a reduced rate when they are built, because an unevidenced claim is worth less than a photographed till roll.",
                max_length=20,
            ),
        ),
    ]
