# Generated by Django 6.0.5 on 2026-07-26 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0013_purchase_points_awarded_purchase_verification_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hot_is_manual",
            field=models.BooleanField(
                default=False,
                help_text="Set by an admin for a recall or safety event. Survives the daily recompute, because the situations that need it are exactly the ones no metric will have noticed yet.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hot_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("trending", "Being bought unusually often"),
                    ("rating_moved", "Rating has moved sharply"),
                    ("manual", "Flagged by an admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hot_since",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this product became worth players' attention. Recomputed daily, except where an admin has flagged it manually.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ActionCentreState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_visited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Visiting clears the badge. It returns only when something genuinely new arrives, so it never becomes a permanent nag about items the player has already decided to ignore.",
                        null=True,
                    ),
                ),
                (
                    "emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Opt-out is honoured immediately and permanently — including for the onboarding sequence.",
                    ),
                ),
                ("onboarding_emails_sent", models.PositiveIntegerField(default=0)),
                ("last_email_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_centre_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
