# Generated by Django 6.0.5 on 2026-07-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0014_product_hot_is_manual_product_hot_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="held_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="hold_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("velocity", "Unusually many receipts in a short time"),
                    ("high_value", "Unusually large receipt"),
                ],
                db_index=True,
                help_text="Withholds points pending review. The receipt is still read and still counts toward ratings — holding the data as well as the reward would punish the honest majority to inconvenience a few.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MetricsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_on", models.DateField(db_index=True)),
                ("line_items", models.PositiveIntegerField(default=0)),
                ("alias_hits", models.PositiveIntegerField(default=0)),
                ("fuzzy_matches", models.PositiveIntegerField(default=0)),
                ("adjudicated", models.PositiveIntegerField(default=0)),
                ("player_resolved", models.PositiveIntegerField(default=0)),
                ("unmatched", models.PositiveIntegerField(default=0)),
                ("prompts_pending", models.PositiveIntegerField(default=0)),
                ("prompts_resolved", models.PositiveIntegerField(default=0)),
                ("unverified_products", models.PositiveIntegerField(default=0)),
                ("retired_products", models.PositiveIntegerField(default=0)),
                ("demoted_aliases", models.PositiveIntegerField(default=0)),
                ("aliases_needing_review", models.PositiveIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means the whole platform.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_snapshots",
                        to="spendium.store",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_on"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("taken_on", "store"),
                        name="one_metrics_snapshot_per_store_per_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("store__isnull", True)),
                        fields=("taken_on",),
                        name="one_platform_metrics_snapshot_per_day",
                    ),
                ],
            },
        ),
    ]
