# Generated by Django 6.0.5 on 2026-07-26 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0015_purchase_held_at_purchase_hold_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_stopped",
                    models.BooleanField(
                        default=False,
                        help_text="Tick this to stop Spendium calling any AI model. Receipts already uploaded stay safe and unread until you untick it, and are then processed automatically — nothing is lost and no player loses points. Untick to resume.",
                        verbose_name="Stop all AI spending now",
                    ),
                ),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional: what made you stop it. Useful to whoever asks later.",
                        max_length=300,
                    ),
                ),
                (
                    "stopped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency stop",
                "verbose_name_plural": "Emergency stop",
            },
        ),
    ]
