# Generated by Django 6.0.5 on 2026-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0016_emergencystop"),
    ]

    operations = [
        migrations.AddField(
            model_name="productratingsnapshot",
            name="purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
