# Generated by Django 6.0.5 on 2026-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0017_productratingsnapshot_purchase_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="min_rating_responses",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Verified responses before a product rating is shown at all. 0 means follow the shared survey threshold, which Polium also uses — set it here to let a catalogue being bootstrapped show something without changing what Polium pays out. Raise it as players arrive.",
            ),
        ),
    ]
