# Generated by Django 6.0.5 on 2026-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0018_matchconfig_min_rating_responses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchconfig",
            name="prompt_budget",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Maximum disambiguation prompts shown per receipt before the player asks for more. Players who see fifteen icons ignore all of them. Also caps work: one matching cascade runs per prompt shown, on every view of the purchase. Zero disables prompting entirely.",
            ),
        ),
    ]
