# Generated by Django 6.0.5 on 2026-08-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendium", "0019_alter_matchconfig_prompt_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreRatingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_on", models.DateField(db_index=True)),
                ("score", models.DecimalField(decimal_places=3, max_digits=4)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("verified_count", models.PositiveIntegerField(default=0)),
                (
                    "points_per_dollar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_snapshots",
                        to="spendium.store",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_on"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "taken_on"),
                        name="one_snapshot_per_store_per_day",
                    )
                ],
            },
        ),
    ]
