# Generated by Django 6.0.5 on 2026-05-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("office", models.CharField(max_length=200)),
                ("external_reference", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "current_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklisted_at", models.DateTimeField(blank=True, null=True)),
                ("engagement_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicates",
                    models.ManyToManyField(blank=True, to="polium.candidate"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blacklisted_at", models.DateTimeField()),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating_at_blacklist",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "rating_at_lift",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_history",
                        to="polium.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("election_date", models.DateField()),
                ("external_reference", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="polium.election",
            ),
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sqid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("active_engagement", models.PositiveIntegerField(default=0)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("level", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jurisdictions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="polium.jurisdiction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="election",
            name="jurisdiction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elections",
                to="polium.jurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="jurisdiction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="polium.jurisdiction",
            ),
        ),
        migrations.CreateModel(
            name="JurisdictionDuplicateFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_flags",
                        to="polium.jurisdiction",
                    ),
                ),
                (
                    "flagging_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdiction_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "points_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagged_as_duplicate_of",
                        to="polium.jurisdiction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JurisdictionFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depth",
                    models.CharField(
                        choices=[
                            ("this", "This level only"),
                            ("all", "This level and below"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="polium.jurisdiction",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_jurisdictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office", models.CharField(max_length=300)),
                ("jurisdiction", models.CharField(max_length=300)),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_history",
                        to="polium.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "office histories",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VoteDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_on_social", models.BooleanField(default=False)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_declarations",
                        to="polium.candidate",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_declarations",
                        to="polium.election",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="jurisdiction",
            index=models.Index(
                fields=["status", "active_engagement"],
                name="polium_juri_status_e611af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jurisdiction",
            index=models.Index(
                fields=["parent", "status"], name="polium_juri_parent__1bfc6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["jurisdiction", "election_date"],
                name="polium_elec_jurisdi_802955_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["jurisdiction", "current_rating"],
                name="polium_cand_jurisdi_da23d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["engagement_count"], name="polium_cand_engagem_694ab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["is_blacklisted"], name="polium_cand_is_blac_688bdd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jurisdictionduplicateflag",
            unique_together={("flagging_player", "flagged_jurisdiction")},
        ),
        migrations.AlterUniqueTogether(
            name="jurisdictionfollow",
            unique_together={("player", "jurisdiction")},
        ),
        migrations.AlterUniqueTogether(
            name="votedeclaration",
            unique_together={("player", "election")},
        ),
    ]
