# Generated by Django 6.0.5 on 2026-05-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polium", "0002_alter_candidate_sqid_alter_election_sqid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacklisthistory",
            name="lifted_at",
        ),
        migrations.RemoveField(
            model_name="blacklisthistory",
            name="rating_at_lift",
        ),
        migrations.AddField(
            model_name="blacklisthistory",
            name="blacklisted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blacklist_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blacklisthistory",
            name="forum_discussion_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="blacklisthistory",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="election_win_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="endorsement_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="endorsement_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_endorsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="pre_election_rating_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="rating_below_threshold_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
