# Generated by Django 6.0.5 on 2026-06-07 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polium", "0003_blacklist_redesign"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="election",
            unique_together={("jurisdiction", "name", "election_date")},
        ),
    ]
