# Generated by Django 6.0.5 on 2026-06-07 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polium", "0004_election_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("jurisdiction", "name", "office")},
        ),
    ]
